### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by lionirdeadman** [yumiris/SPV3.Release#1]
This topic originally covered `Removal of tracking statistics`, but for consistency with the other issues (#2 and #3), it's been turned into a general topic that covers the **Statistics** section of the proposal document.

The original text by @lionirdeadman can be read below. Cheers!

~ yumiris

---

Tracking installations will not give you the amount of people playing. In fact, I'll probably be the first person to muddy the waters while I try to make it work consistently in wine.

Tracking statistics are impersonal by design, they don't know you and you don't know them making it just a useless metric number for all we care. We are people, not numbers.

Tracking statistics are bad user experience because the program will execute an action without the user's knowledge.

If all you want is a useless number, the request for the message shown in the launcher works fine. Thank you.

**Comment by YuMiris** [comment]
> Tracking installations will not give you the amount of people playing.

No, but it will let us know how many people have attempted to install SPV3, and the success:failure ratio. Depending on how the tracking is implemented, we might get some non-personal information such as OS version and hardware specifications.

Asides from the ability to find reasons for potential issues, it's also to determine the popularity of the release.

> Tracking statistics are impersonal by design, they don't know you and you don't know them making it just a useless metric number for all we care. We are people, not numbers.

You won't directly benefit from the tracking, but the developers will directly benefit from it. End-users will indirectly benefit from the statistics if the statistics facilitate in improving SPV3.

> Tracking statistics are bad user experience because the program will execute an action without the user's knowledge.

I believe we are transparent enough with tracking, and tracking won't be conducted randomly. We will document when tracking is conducted, thus the user shouldn't face any surprises.

Also, programs conducting invisible actions in the background are not a bad user experience because they have no impact on the user, unless they are malicious in nature and thereby affect either the user's privacy or system. Neither occurs in this context.

> If all you want is a useless number, the request for the message shown in the launcher works fine. Thank you.

The MOTD is retrieved from GitHub, thus resulting vague and skewed statistics (e.g. due to dynamic IP addresses). By utilising an unique string that's stored on the computer for identification, practically speaking, the statistics will be more accurate.

As mentioned above, we will also track the outcome of the installation, launch success and other actions that will help us determine the failure rates. It's not just vanity. 😉

**Comment by YuMiris** [comment]
> In fact, I'll probably be the first person to muddy the waters while I try to make it work consistently in wine.

Considering that the unique ID is persistent on the computer, you'd have to go out of your way to delete it from `%APPDATA%` to reset the counter. Assuming we'll get quite a load of downloads and scenarios like yours are rare and won't happen too frequently, a small inaccuracy won't be a significant issue.

**Comment by SubhadeepJasu** [comment]
We would like to avoid getting personally identifiable information. Assuming that we're "treating people like numbers" is taking it a bit too far IMO. Also in wine 32, you can install SPV3. It has been confirmed that you'll not be able to play with a mouse. You may need a gamepad to play it.

**Comment by YuMiris** [comment]
> Success:failure ratio is unimportant if you don't have a way to fix the issues therefore what you really want is to know what issues people have had which is already achieved by the Discord and Reddit channels of communication.

Re: **As mentioned above, we will also track the outcome of the installation, launch success and other actions that will help us determine the failure rates.** 

Of course, communication with the users will also be conducted. However, statistics & communication > only communication.

> Popularity of the release would be incredibly inaccurate as I've stated elsewhere.

Re: **Considering that the unique ID is persistent on the computer, you'd have to go out of your way to delete it from %APPDATA% to reset the counter. Assuming we'll get quite a load of downloads and scenarios like yours are rare and won't happen too frequently, a small inaccuracy won't be a significant issue.**

Hence, "incredibly inaccurate" is an exaggeration in this practical scenario. Linux/WINE users who'll delete their WINEPREFIX folder are a significant minority.

> Statistics really don't help to improve SPV3 because it doesn't say what the issues are. This is done by communication, not tracking.

Asides from tracking the outcome of various actions, we could track exception errors. Communication will also be considered, though that'll burden the user with having to be specific.

> I would certainly say that it does affect the user's privacy. It does contact an unknown server and give that server unknown information. Also, unless you give the ability to not send this information, being informed that the action will be done doesn't improve the user experience.

Re: **I believe we are transparent enough with tracking, and tracking won't be conducted randomly. We will document when tracking is conducted, thus the user shouldn't face any surprises.**

An "unknown server" has no relevance to the privacy of the user assuming that:

- we will specify what data gets sent (and we will);
- connection is carried out securely (which it will);
- personal data - e.g., IP addresses & usernames - isn't logged (which it won't).

Though, the server that will be called will also be specified in the documentation. As such, it won't be "unknown".

> Also, unless you give the ability to not send this information, being informed that the action will be done doesn't improve the user experience.

We might include an option to disable tracking. I have yet to understand why anyone would remotely care about _non-personal_ data being automatically collected, and this comes from someone who does value the privacy of personal/confidential data.

**Comment by YuMiris** [comment]
Refer to bd0764641e8b3c7cc786f8b7503a9b28bf7cb0dd for elaboration on what is being tracked and why!

**Comment by YuMiris** [comment]
Refer to 143607c47e55af075603ab52a77fcebe0d732d95 on our attempts at keeping exception logs as anonymous as practically feasible.

**Comment by yumiris** [comment]
For the implementation and further technical documentation, refer to [SPV3.Statistics](https://github.com/yumiris/SPV3.Statistics).

**Comment by yumiris** [comment]
Revision 781ab02cf09466adda0de95b610ba77ddd51dfc7 effectively discards the usage of statistics. 

Figuring out a solution that is ...

- completely anonymous
- reliable and robust
- cheap or free
- maintainable

... is practically impossible, given the current circumstances.
